pipeline:
  name: pipeline1
  identifier: pipeline1
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: pipeline1-stage
        identifier: pipeline1stage
        tags: {}
        template:
          templateRef: account.test2stagetemplate
          versionLabel: 1.0.4
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
